# Generated by Django 3.2.14 on 2022-10-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventhead', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('eventimage', models.ImageField(blank=True, null=True, upload_to='static/events')),
            ],
        ),
        migrations.CreateModel(
            name='FundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundName', models.CharField(max_length=100)),
                ('FundType', models.CharField(max_length=100)),
                ('FundDescription', models.CharField(max_length=100)),
                ('FundImage', models.ImageField(blank=True, null=True, upload_to='static/products')),
                ('Imgname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventimage', models.ImageField(blank=True, null=True, upload_to='static/gallery')),
            ],
        ),
    ]
