# Generated by Django 3.2.14 on 2022-10-29 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationid', models.CharField(max_length=100)),
                ('studentid', models.CharField(max_length=100)),
                ('studentname', models.CharField(max_length=100)),
                ('nameoncard', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=100)),
                ('cardcvv', models.CharField(max_length=100)),
                ('expiredate', models.CharField(max_length=100)),
                ('fundamount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobrole', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('filename', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderid', models.CharField(max_length=100)),
                ('receiverid', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('timing', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicmessgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=100)),
                ('studentmessage', models.CharField(max_length=100)),
                ('timing', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('Faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('Rollnumber', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('semister', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=100)),
                ('StudentType', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
