# Generated by Django 3.2.14 on 2022-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderid', models.CharField(max_length=100)),
                ('receiverid', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('timing', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
