# Generated by Django 3.2.14 on 2022-10-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facultyname', models.CharField(max_length=100)),
                ('facultyid', models.CharField(max_length=50)),
                ('facultyemail', models.CharField(max_length=50)),
                ('facultypassword', models.CharField(max_length=50)),
                ('facultydept', models.CharField(max_length=50)),
                ('facultyroll', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
